name: Deploy to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  PROJECT_ID: ${{ secrets.POC_PROJECT_ID}} #provide your gcp-project-id
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTR_NME}}
  GKE_ZONE: ${{ secrets.GKE_ZONE}}
  IMAGE_NAME: ${{ secrets.GKE_ZONE}}-docker.pkg.dev/${{ secrets.POC_PROJECT_ID }}/poc-images/nginx-secure:1.25

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.POC_SVCACCT_SECRET }} # Using the GitHub Secret here

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Configure Docker to use Google Cloud credentials
        run: gcloud auth configure-docker ${{ secrets.GKE_ZONE}}-docker.pkg.dev

      - name: Push Docker image to Artifact Registry
        run: docker push ${{ env.IMAGE_NAME }}

      - name: Helm Lint & Package
        run: |
          helm lint helm/nginx-chart
          helm package helm/nginx-chart
          helm install nginx-chart helm/nginx-chart --namespace poc-test --create-namespace --set image.repository=${{ env.IMAGE_NAME }} --set image.tag=1.25
  

